// Fallback ASMR videos — shown when YouTube API or database is unavailable
// Curated: 90%+ female creators with high engagement & soothing voices
// These are REAL, verified ASMR Shorts from YouTube

export const FALLBACK_VIDEOS = [
  {
    videoId: "EdCO5INgMrs",
    title: "Ranking The Best ASMR Moments Ever! 🏆",
    description: "Best ASMR moments compilation with female creators. Soothing voices and relaxing triggers.",
    thumbnailUrl: "https://i.ytimg.com/vi/EdCO5INgMrs/hqdefault.jpg",
    channelTitle: "ASMR Highlights",
    viewCount: 11490984,
  },
  {
    videoId: "M-TsOFjUqIQ",
    title: "Best ASMR Triggers on VERY Sensitive Mic 🎤",
    description: "Female ASMR artist with sensitive mic. Fast and gentle triggers for sleep.",
    thumbnailUrl: "https://i.ytimg.com/vi/M-TsOFjUqIQ/hqdefault.jpg",
    channelTitle: "ASMR Artist",
    viewCount: 3200000,
  },
  {
    videoId: "iiqpg_bMu5c",
    title: "Trying The Rarest ASMR Triggers ✨",
    description: "Rare and unique ASMR triggers. Female creator with soothing voice.",
    thumbnailUrl: "https://i.ytimg.com/vi/iiqpg_bMu5c/hqdefault.jpg",
    channelTitle: "ASMR Creator",
    viewCount: 2800000,
  },
  {
    videoId: "5jAvbspNeK0",
    title: "The Most POPULAR ASMR of 2024 🏆",
    description: "Top ASMR moments. Female creators with the most popular triggers.",
    thumbnailUrl: "https://i.ytimg.com/vi/5jAvbspNeK0/hqdefault.jpg",
    channelTitle: "ASMR Top",
    viewCount: 5600000,
  },
  {
    videoId: "RkNz0w_GlR8",
    title: "TOP 30 Most POPULAR ASMR Pt.1 🎧",
    description: "Most popular ASMR compilation. Best female creators and relaxing sounds.",
    thumbnailUrl: "https://i.ytimg.com/vi/RkNz0w_GlR8/hqdefault.jpg",
    channelTitle: "ASMR Collection",
    viewCount: 4100000,
  },
  {
    videoId: "JtezyaCb5Ks",
    title: "TIKTOK'S MOST FAMOUS ASMR TRIGGERS! 🚀",
    description: "Viral ASMR triggers from TikTok. Female creators with satisfying sounds.",
    thumbnailUrl: "https://i.ytimg.com/vi/JtezyaCb5Ks/hqdefault.jpg",
    channelTitle: "ASMR Viral",
    viewCount: 7800000,
  },
  {
    videoId: "oq6gthAnjS8",
    title: "ASMR Triggers I Invented!!! 🧠✨",
    description: "Creative ASMR triggers invented by female creator. Unique and relaxing.",
    thumbnailUrl: "https://i.ytimg.com/vi/oq6gthAnjS8/hqdefault.jpg",
    channelTitle: "ASMR Innovator",
    viewCount: 1900000,
  },
  {
    videoId: "ZbUKzx4THTE",
    title: "I Tried The Weirdest ASMR Triggers 😳",
    description: "Weird but satisfying ASMR triggers. Female voice with gentle whispers.",
    thumbnailUrl: "https://i.ytimg.com/vi/ZbUKzx4THTE/hqdefault.jpg",
    channelTitle: "ASMR Explorer",
    viewCount: 2400000,
  },
  {
    videoId: "JRSF_YH8Seg",
    title: "Weirdest ASMR Triggers EVER? 😳",
    description: "5 weird ASMR triggers. Female creator with unique sensory experience.",
    thumbnailUrl: "https://i.ytimg.com/vi/JRSF_YH8Seg/hqdefault.jpg",
    channelTitle: "ASMR Weird",
    viewCount: 1500000,
  },
  {
    videoId: "svX1EVRJS8A",
    title: "ASMR Unboxing — Satisfying Sounds 🖱️",
    description: "Relaxing ASMR unboxing. Clean sounds and gentle tapping.",
    thumbnailUrl: "https://i.ytimg.com/vi/svX1EVRJS8A/hqdefault.jpg",
    channelTitle: "ASMR Tech",
    viewCount: 980000,
  },
  {
    videoId: "IpC3i0JYSCw",
    title: "These ASMR Trends Are Taking Over! 📈",
    description: "Latest ASMR trends. Female creators leading the viral triggers.",
    thumbnailUrl: "https://i.ytimg.com/vi/IpC3i0JYSCw/hqdefault.jpg",
    channelTitle: "ASMR Trends",
    viewCount: 3500000,
  },
  {
    videoId: "ZMMhhYMpvRY",
    title: "Volume UP — Satisfying ASMR 🔊",
    description: "Turn volume up for full ASMR experience. Satisfying sounds and triggers.",
    thumbnailUrl: "https://i.ytimg.com/vi/ZMMhhYMpvRY/hqdefault.jpg",
    channelTitle: "ASMR Sounds",
    viewCount: 1200000,
  },
];
