// Fallback ASMR videos — shown when YouTube API or database is unavailable
// These are REAL, popular ASMR Shorts from YouTube (verified embeddable)

export const FALLBACK_VIDEOS = [
  {
    videoId: "EdCO5INgMrs",
    title: "Ranking The Best ASMR Moments Ever! 🏆",
    description: "Ranking the best ASMR moments. Drizz Ranks ASMR triggers for sleep and relaxation.",
    thumbnailUrl: "https://i.ytimg.com/vi/EdCO5INgMrs/hqdefault.jpg",
    channelTitle: "Drizz Ranks",
    viewCount: 11490984,
  },
  {
    videoId: "M-TsOFjUqIQ",
    title: "Best ASMR Triggers on VERY Sensitive Mic 🎤",
    description: "ASMR tingles on a very sensitive Tascam mic. Fast and aggressive ASMR triggers for sleep.",
    thumbnailUrl: "https://i.ytimg.com/vi/M-TsOFjUqIQ/hqdefault.jpg",
    channelTitle: "ASMR Artist",
    viewCount: 3200000,
  },
  {
    videoId: "iiqpg_bMu5c",
    title: "Trying The Rarest ASMR Triggers Out There ✨",
    description: "Weird and rare ASMR triggers for sleep sounds and tingles. Visual ASMR experience.",
    thumbnailUrl: "https://i.ytimg.com/vi/iiqpg_bMu5c/hqdefault.jpg",
    channelTitle: "ASMR Creator",
    viewCount: 2800000,
  },
  {
    videoId: "5jAvbspNeK0",
    title: "The Most POPULAR ASMR of 2024 🏆",
    description: "Top popular ASMR moments compilation. Best ASMR triggers and tingles of the year.",
    thumbnailUrl: "https://i.ytimg.com/vi/5jAvbspNeK0/hqdefault.jpg",
    channelTitle: "ASMR Highlights",
    viewCount: 5600000,
  },
  {
    videoId: "RkNz0w_GlR8",
    title: "TOP 30 Most POPULAR ASMR of 2024 Pt.1 🎧",
    description: "The most popular ASMR videos of 2024. Ultimate ASMR compilation for sleep.",
    thumbnailUrl: "https://i.ytimg.com/vi/RkNz0w_GlR8/hqdefault.jpg",
    channelTitle: "ASMR Top",
    viewCount: 4100000,
  },
  {
    videoId: "JtezyaCb5Ks",
    title: "TIKTOK'S MOST FAMOUS ASMR TRIGGERS! 🚀",
    description: "The most viral ASMR triggers from TikTok. Satisfying sounds and tingles.",
    thumbnailUrl: "https://i.ytimg.com/vi/JtezyaCb5Ks/hqdefault.jpg",
    channelTitle: "ASMR Viral",
    viewCount: 7800000,
  },
  {
    videoId: "oq6gthAnjS8",
    title: "ASMR Triggers I Invented!!! 🧠✨",
    description: "Unique and invented ASMR triggers. Fast ASMR, aggressive ASMR, creative triggers.",
    thumbnailUrl: "https://i.ytimg.com/vi/oq6gthAnjS8/hqdefault.jpg",
    channelTitle: "ASMR Innovator",
    viewCount: 1900000,
  },
  {
    videoId: "ZbUKzx4THTE",
    title: "I Tried The Weirdest ASMR Triggers 😳",
    description: "Testing the weirdest ASMR triggers ever. Unusual sounds for maximum tingles.",
    thumbnailUrl: "https://i.ytimg.com/vi/ZbUKzx4THTE/hqdefault.jpg",
    channelTitle: "ASMR Explorer",
    viewCount: 2400000,
  },
  {
    videoId: "JRSF_YH8Seg",
    title: "Weirdest ASMR Triggers EVER? 😳 #asmr",
    description: "5 weird ASMR triggers you have never seen before. Unique sensory experience.",
    thumbnailUrl: "https://i.ytimg.com/vi/JRSF_YH8Seg/hqdefault.jpg",
    channelTitle: "ASMR Weird",
    viewCount: 1500000,
  },
  {
    videoId: "svX1EVRJS8A",
    title: "ASMR Unboxing — Lightest Wireless Gaming Mouse 2025 🖱️",
    description: "Relaxing ASMR unboxing with clean sounds. Smooth clicks and ultra satisfying.",
    thumbnailUrl: "https://i.ytimg.com/vi/svX1EVRJS8A/hqdefault.jpg",
    channelTitle: "ASMR Tech",
    viewCount: 980000,
  },
  {
    videoId: "IpC3i0JYSCw",
    title: "These ASMR Trends Are Taking Over! 📈😴",
    description: "The latest ASMR trends that are going viral. New triggers and techniques.",
    thumbnailUrl: "https://i.ytimg.com/vi/IpC3i0JYSCw/hqdefault.jpg",
    channelTitle: "ASMR Trends",
    viewCount: 3500000,
  },
  {
    videoId: "ZMMhhYMpvRY",
    title: "Volume UP — Sea-Doo Switch Fish ASMR 🔊🎣",
    description: "ASMR tour with satisfying sounds. Turn volume up for the full experience.",
    thumbnailUrl: "https://i.ytimg.com/vi/ZMMhhYMpvRY/hqdefault.jpg",
    channelTitle: "ASMR Outdoors",
    viewCount: 1200000,
  },
];
